### ISSUE TITLE
Jisc demo

### ISSUE THREAD

**Issue by davidfurlong** [willzeng/cograph#275]
- [x] Have a grid view where the nodes (and their expanded details) tile the screen so that the data can be viewed as a list. Have sorting features.
- [ ] Have a history scrollbar so we can scroll through time and see the changes
- [x] Export data to mathematica / csv
- [x] On bigger graphs the graph moves around / floats a little more which isn't great
- [ ] have fixedness of nodes as a stored server state?
- [x] A very connected graph becomes illegible currently, the distance between nodes should increase and spread out if the graph becomes too dense. 
- [ ] Circular clump of non connected graph would be better as a rectangle to fit the screen
- [x] Collision detection & prevention
- [x] 2 links between 2 nodes which both have titles the titles collide and neither is legible
- [ ] Graphview needs to be optimized for redrawing updates
- [x] #bug Firefox height bug problem #276 
- [ ] Some mobile browsers (very few) didn't work with typeahead
- [ ] Activity feed (potentially in the sidebar)
- [x] Filter on connection type
- [x] Toggle off all filters with one click #279 
- [ ] Show how many nodes per filter
- [x] Different presentations/ views.
- [ ] More Mathematica style analytics available
- [x] Colors based on connections, colors based on filters
- [x] #bug connection colors weren't working sometimes
- [x] #bug graph title cursor keeps moving to the end. Update title on blur
- [x] #bug mouseout bottom of node isn't working as expected #276 
- [ ] #bug mobile jitters left and right
