### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by davidfurlong** [willzeng/cograph#564]
- [x] node text color too light https://github.com/willzeng/graphdocs/issues/567
- [ ] nodes are frequently added off screen [defer to 0.2] https://github.com/willzeng/graphdocs/issues/570
- [ ] search / add when adding connection from inside a node https://github.com/willzeng/graphdocs/pull/566
- [ ] atwho is sticking occassionally [defer to 0.2]
- [ ] add node not working occassionally [needs replication]
- [ ] i just added a bunch of connections and then only 1 was added. on reload they were all gone [needs replication]
- [ ] typing out a +autocomplete without selecting or tabbing doesnt actually link. Should they be blue if linked or something to indicate this or should we change the way it works [defer]
- [x] heroku isn't recompiling the less files into css files ever now. you need to run production to actually get them to compile [this is fixed right?]
- [x] pressing the atwho modal closes the add node !IMPORTANT https://github.com/willzeng/graphdocs/issues/568
- [ ] add node pressing create doesn't keep focus & expand [needs issue]
- [ ] + in description consistency. We either keep them in for all connections or out for all connections. It makes sense to have them in for gridview. So both manually created and + created on both target and source [am not sure what you mean here] describe here: https://github.com/willzeng/graphdocs/issues/571
- [x] share button not working https://github.com/willzeng/graphdocs/issues/569
- [x] escape to cancel connection create
- [x] double click title to edit graph settings
- [ ] link tags in node text view
- [ ] tagging users with @ doesnt work https://github.com/willzeng/graphdocs/issues/576
- [ ] negative expand values https://github.com/willzeng/graphdocs/issues/575

@willzeng
